name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    name: python
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      -run: echo "tested"

  build:
    name: webapp
    runs-on: ubuntu-24.04
    needs: test
    if: github.event_name == 'push'
    steps:
      - run: echo "ran"
